export type Sector = 'SCH'|'VET'|'ADU'|'YOU'|'HED'|'SPO';
export type DocRole = 'application'|'annex'|'working'|'past-review'|'official'|'institutional';
export type FindingState = 'Belgede yok'|'Yetersiz açıklanmış'|'Okunamadı'|'Çelişkili'|'Uygulanamaz'|'Doğrulama bekliyor';
export interface Source {id:string;url:string;title:string;section:string;page:number|null;hash:string;checkedAt:string;version:string;localPath?:string;status:'verified'|'unavailable'|'draft';text?:string}
export interface Criterion {id:string;name:string;max:number;threshold:number;description:string;sourceId:string;sourceSection:string;elements:string[]}
export interface FormField {id:string;title:string;question:string;page:number|null;characterLimit:number|null;criterionIds:string[]}
export interface RuleSet {id:string;callYear:number;actionCode:string;sector:Sector;jurisdiction:string;agency:string;round:string;applicantRole:string;guideVersion:string;formVersion:string;effectiveDate:string;checkedAt:string;sourceUrl:string;sourceSection:string;sourcePage:number|null;contentHash:string;status:'verified'|'draft'|'conflict';supersedes:string|null;mode:'quality'|'allocation'|'accreditation';criteria:Criterion[];totalThreshold:number|null;sources:Source[];formFields:FormField[];formVerified:boolean;limitations:string[];eligibility:EligibilityRule[];budget:BudgetRules}
export interface EligibilityRule {id:string;field:string;label:string;op:'eq'|'min'|'max'|'oneOf';value:string|number|boolean|string[];sourceId:string;sourceSection:string}
export interface BudgetRules {model:'unit'|'lump'|'none';lumpSums:number[];travel?:{min:number;max:number|null;green:number;standard:number}[];individualRate:null;allocationVerified:boolean}
export interface Section {id:string;documentId:string;location:string;heading:string;text:string;readable:boolean;kind:'paragraph'|'cell'|'page'|'form';page?:number;sheet?:string;cell?:string;formula?:string;cachedValue?:string|number|null;version:number}
export interface Extraction {sections:Section[];warnings:string[];complete:boolean;pages:number;suggestedCodes:string[];suggestedYears:number[]}
export interface Project {id:string;title:string;callYear:number;actionCode:string;sector:Sector;country:string;agency:string;round:string;applicantRole:string;organisation:string;facts:Record<string,unknown>;archived:boolean;createdBy:string;updatedBy:string;createdAt:string;updatedAt:string;revision:number;language:'tr'|'en'}
export interface DocumentRecord {id:string;projectId:string;name:string;role:DocRole;purpose:string;hash:string;size:number;status:string;extraction:Extraction|null;error:string|null;createdBy:string;createdAt:string;confirmed:boolean;annexEligible:boolean;version:number}
export interface Evidence {documentId:string;sectionId:string;location:string;quote:string;version:number}
export interface Finding {id:string;title:string;state:FindingState;severity:'critical'|'high'|'medium'|'low';criterionIds:string[];sourceId:string;sourceSection:string;evidence:Evidence[];scannedSections:string[];reason:string;requestedInfo:string;correction:string;draft:string|null;origin:'deterministic'|'ai';status:string;assignee:string|null;version:number}
export interface CriterionAssessment {criterionId:string;score:number;rationale:string;evidence:Evidence[];sourceId:string;elements:{name:string;status:'strong'|'weak'|'missing';reason:string}[]}
export interface ThresholdResult {status:'passed'|'failed'|'unavailable'|'not-applicable';total:number|null;totalPassed:boolean|null;criteria:{id:string;score:number;threshold:number;passed:boolean}[];reason:string}
export interface EligibilityResult {ruleId:string;label:string;status:'eligible'|'ineligible'|'insufficient';actual:unknown;sourceId:string;sourceSection:string}
export interface Assessment {id:string;projectId:string;createdBy:string;createdAt:string;status:string;revision:number;ruleSet:RuleSet;documents:DocumentRecord[];sections:Section[];findings:Finding[];eligibility:EligibilityResult[];criteria:CriterionAssessment[];threshold:ThresholdResult;coverage:{total:number;readable:number;complete:boolean};aiStatus:string;model:string;promptVersion:string;cacheKey:string;mode:'original'|'adaptation';error:string|null}
export interface User {id:string;name:string;email:string;role:'owner'|'member';active:boolean}
export interface Task {id:string;projectId:string;title:string;assignee:string;status:string;reviewer:string|null;completionEvidence:string;createdBy:string;updatedBy:string;version:number;createdAt:string}
export interface BudgetLine {id:string;projectId:string;activityId:string;label:string;category:string;participants:number;days:number;unitCost:number|null;planned:number;requested:number|null;awarded:number|null;country:string;green:boolean;distance:number|null;sourceId:string|null}
